Data Dictionary Production For Inform Visualization
CDCgov/covid19-forecast-hub pull request #118
Opened 2024-11-29 15:39 UTC by AFg6K7h4fhy2

For the scope of this PR, please reference issue #93 .

2024-11-29 18:05 UTC, AFg6K7h4fhy2 commented
Items that require changes:

* Relative imports.
* Checks for the existence or status of certain data files prior to use.
* Docstring formatting.
* Conditions for overwriting `csvs` in `./output/`.
* Naming conventions for the generated `csvs`.
* Handling presence / non-presence combinations for data files prior to use.

2024-11-29 18:56 UTC, AFg6K7h4fhy2 commented
For `gen_tru_csv.R`, I remembered that `forecasttools` has `recode_locations`. The file should be updated.

2024-11-29 20:35 UTC, AFg6K7h4fhy2 commented
The `args` for `pull_nhsn` in `gen_map_csv.R` can be abstracted further (e.g. the reference date argument).

2024-11-29 21:14 UTC, AFg6K7h4fhy2 commented
Move `./weekly-summaries/utils/` to `./src/code/` (from SB).

2024-11-29 21:18 UTC, AFg6K7h4fhy2 commented
The folder structure ought (as presently decided) to look like:

* `weekly-summaries` (name subject to change)
  * `all-forecasts` (name subject to change)
    * `YYYY-MM-DD` (i.e. the reference date)
      * `file.csv` (name subject to change)
  * etc...

2024-11-29 21:24 UTC, AFg6K7h4fhy2 commented
Generate files for first week of submission, account for the data anomalies. Does Inform want us to take into account exclusions? SB: exclude some locations for the first week of submissions.

2024-11-29 21:34 UTC, AFg6K7h4fhy2 commented
Should `reference_date` be a command line argument?

Maybe some way of checking that the generated `reference_date` is a number plus the latest week as extracted from the generated csvs.

2024-11-29 21:58 UTC, AFg6K7h4fhy2 commented
For / By Monday, December 02, 2024:

* SB reviews the present state of the PR
  * Review docstrings.
  * Review synching of README.md and `output` content.
  * Review the three scripts in `utils`.
* UPX3 modifies the file output paths and file name references
* UPX3 modifies the excluding of locations behavior.
* UPX3 modifies relative pathing used.
* UPX3 cleans docstrings and comments.
* DHM review PR.

2024-11-29 22:28 UTC, sbidari commented
forecasts and truth data for `US` is missing (in all three csvs)

`all_forecasts.csv` 
 - rename column name `model_id` -> `model`
 - add columns `forecast_teams`, `forecast_fullnames`
 - we also want to include the baseline model "CovidHub-baseline" here

2024-11-29 22:45 UTC, sbidari requested changes
Left some comments. Will review in more detail on Monday when you've had the chance to update things.

2024-11-29 22:45 UTC, sbidari commented on weekly-summaries/utils/gen_forecast_data.R
> +#' submissions from the `CovidHub` model. The
```suggestion
#' This script fetches all forecast submissions from the 
#' covid19-forecast-hub based on the 
#' `reference_date`. The 
```

2024-11-29 22:45 UTC, sbidari commented on weekly-summaries/utils/gen_forecast_data.R
> +#     forecast_fullnames
`forecast_teams` and `forecast_fullnames` are missing

2024-11-29 22:45 UTC, sbidari commented on weekly-summaries/utils/gen_truth_data.R
> +#' data (using the `get_target_data.r` script).
```suggestion
#' observed COVID-19 hospital
#' admissions data for all states 
#' (including US, DC, and Puerto Rico) 
#' and processes it into the required format 
#' for `truth_data.csv`. The data is sourced 
#' from the NHSN hospital respiratory
#' data (https://www.cdc.gov/nhsn/psc/hospital-respiratory-reporting.html).
```

2024-11-30 06:47 UTC, AFg6K7h4fhy2 commented on weekly-summaries/utils/gen_forecast_data.R
> +#     forecast_fullnames
I will address early Monday; good catch!

2024-12-02 15:27 UTC, AFg6K7h4fhy2 commented
Re: <https://github.com/CDCgov/covid19-forecast-hub/pull/118#issuecomment-2508709026>

Example `metadata` file: <https://github.com/CDCgov/covid19-forecast-hub/blob/e0e1369c852272c4fe6eeacd3d9ea47e6fc77328/model-metadata/CMU-TimeSeries.yml>. The `forecast_name` will come from `model_name` and the `forecast_team` will come from `team_name`. 

Also, DHM mentions: the `pivot_hubverse_quantiles_wider` can accept any names, not just the ones used by default. Minor lapse on the author's end here...

2024-12-02 15:33 UTC, AFg6K7h4fhy2 commented
What should the `csv` files be named? Currently:

* `map.csv`
* `truth_data.csv`
* `all_forecasts.csv`

2024-12-02 15:50 UTC, sbidari commented
I suggest the following structure:
`weekly-summaries\reference-date\` 
- `reference-date-map.csv`
- `reference-date-truth_data.csv`
- `reference-date-all_forecasts.csv`

where reference-date is of format `YYYY-MM-DD`. 
We add a new folder named by corresponding reference-date every week, so reference-date should not be hardcoded in the codes.

2024-12-02 15:58 UTC, AFg6K7h4fhy2 commented
Re: <https://github.com/CDCgov/covid19-forecast-hub/pull/118#issuecomment-2511902915>

This works, thank you SB.

2024-12-02 19:13 UTC, AFg6K7h4fhy2 commented
For the `all-forecasts` csv, want all submitted models (incl. the baseline and the ensemble).

2024-12-02 19:18 UTC, AFg6K7h4fhy2 commented
GitHub Actions (GHA) will likely break relative paths:

```r
# store base metadata path for use later
model_metadata_path <- "../../model-metadata/" 

# get `covid19-forecast-hub` content
base_hub_path <- "../../"  
hub_content <- hubData::connect_hub(base_hub_path)
```

These should change to arguments to the argparse. Multiple arguments: one for output folder and one for base hub path.

2024-12-02 19:20 UTC, AFg6K7h4fhy2 commented
Error if the current reference date's ensemble is not found: 

<details>
<summary>
Ensemble file behavior:
</summary>

```r
# load the latest ensemble data from the 
# model-output folder
ensemble_folder <- "../../model-output/CovidHub-ensemble/"
ensemble_file_current <- file.path(ensemble_folder, paste0(ref_date, "-CovidHub-ensemble.csv"))
if (file.exists(ensemble_file_current)) {
  ensemble_file <- ensemble_file_current
} else {
  ensemble_files <- list.files(
    ensemble_folder, 
    pattern = "\\.csv$", 
    full.names = TRUE
  )
  if (length(ensemble_files) == 0) {
    stop("No ensemble CSV files found in the directory.")
  }
  ensemble_file <- tail(ensemble_files, 1)
  message("Using the latest file: ", ensemble_file)
}
ensemble_data <- readr::read_csv(ensemble_file)
```
</details>

This note originated in a call between DHM, SB, TM.

2024-12-02 20:19 UTC, AFg6K7h4fhy2 commented
Bug!

Printing `model_metadata` returns:

```
# A tibble: 11 × 19
   model_id              team_abbr model_abbr team_name model_name model_version
   <chr>                 <chr>     <chr>      <chr>     <chr>      <chr>        
 1 CEPH-Rtrend_covid     CEPH      Rtrend_co… CEPH Lab… Rtrend CO… NA           
 2 CMU-TimeSeries        CMU       TimeSeries Carnegie… AR ensemb… 1.0          
 3 CMU-TimeSeries        CMU       TimeSeries Carnegie… AR ensemb… 1.0          
 4 JHU_CSSE-CSSE_Ensemb… JHU_CSSE  CSSE_Ense… The Cent… CSSE Ense… NA           
 5 MOBS-GLEAM_COVID      MOBS      GLEAM_COV… MOBS Lab… GLEAM COV… 1.0          
 6 Metaculus-cp          Metaculus cp         Metaculus Metaculus… 1.0          
 7 OHT_JHU-nbxd          OHT_JHU   nbxd       One Heal… NBEATS ex… NA           
 8 OHT_JHU-nbxd          OHT_JHU   nbxd       One Heal… NBEATS ex… NA           
 9 UM-DeepOutbreak       UM        DeepOutbr… Universi… DeepOutbr… 1.0          
10 UMass-ar6_pooled      UMass     ar6_pooled UMass-Am… AR(6) mod… 1.0          
11 UMass-gbqr            UMass     gbqr       UMass-Am… gradient … 1.0
```

Where are the `CovidHub-ensemble.yaml` and `CovidHub-baseline.yaml`? Changing `model_contributors: []` to 

```
model_contributors: [
    { "name": "Test", "affiliation": "Test", "email": "test@test.edu" }
]
```

produces

```
# A tibble: 12 × 19
   model_id              team_abbr model_abbr team_name model_name model_version
   <chr>                 <chr>     <chr>      <chr>     <chr>      <chr>        
 1 CEPH-Rtrend_covid     CEPH      Rtrend_co… CEPH Lab… Rtrend CO… NA           
 2 CMU-TimeSeries        CMU       TimeSeries Carnegie… AR ensemb… 1.0          
 3 CMU-TimeSeries        CMU       TimeSeries Carnegie… AR ensemb… 1.0          
 4 CovidHub-baseline     CovidHub  baseline   CovidHub… CovidHub … 1.0          
 5 JHU_CSSE-CSSE_Ensemb… JHU_CSSE  CSSE_Ense… The Cent… CSSE Ense… NA           
 6 MOBS-GLEAM_COVID      MOBS      GLEAM_COV… MOBS Lab… GLEAM COV… 1.0          
 7 Metaculus-cp          Metaculus cp         Metaculus Metaculus… 1.0          
 8 OHT_JHU-nbxd          OHT_JHU   nbxd       One Heal… NBEATS ex… NA           
 9 OHT_JHU-nbxd          OHT_JHU   nbxd       One Heal… NBEATS ex… NA           
10 UM-DeepOutbreak       UM        DeepOutbr… Universi… DeepOutbr… 1.0          
11 UMass-ar6_pooled      UMass     ar6_pooled UMass-Am… AR(6) mod… 1.0          
12 UMass-gbqr            UMass     gbqr       UMass-Am… gradient … 1.0 
```

So `model_contributors` can't be empty. Also, there seems to be some duplicates in the rows listed. @dylanhmorris @sbidari

2024-12-02 20:22 UTC, AFg6K7h4fhy2 commented
There is this warning as well that is generated from the author's code below:

_Warning_

```
Warning message:
In dplyr::left_join(dplyr::mutate(dplyr::mutate(forecasttools::pivot_hubverse_quantiles_wider(hubverse_table = current_forecasts,  :
  Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 213 of `x` matches multiple rows in `y`.
ℹ Row 1 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship = "many-to-many"` to silence this warning.
```

_Code_

```
dplyr::left_join(
    model_metadata, by = "model_id") |>
```

2024-12-02 20:27 UTC, dylanhmorris commented
Good catch @AFg6K7h4fhy2. @sbidari could you edit the metadata to list yourself and/or (as you prefer) the COVIDHub team (with the overall contact email) as model contributors on the Hub models? Thanks!

2024-12-02 20:30 UTC, AFg6K7h4fhy2 commented
Re: <https://github.com/CDCgov/covid19-forecast-hub/pull/118#issuecomment-2512740542>

The author will pull once issue #120 is completed.

2024-12-02 21:45 UTC, dylanhmorris submitted a review, later dismissed
Thanks @AFg6K7h4fhy2. A few minor things, mostly style.

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +  dplyr::filter(reference_date == as.Date(ref_date)) |>
```suggestion
  dplyr::filter(reference_date == as.Date(!!ref_date)) |>
```

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +  dplyr::filter(reference_date == as.Date(ref_date)) |>
See https://github.com/cdcent/cfa-predict-handbook/blob/3f641ecce3070868e77d881546fe87351722d8ad/docs/r_coding_tips.md#use-either-variable_name-or-envvariable_name-to-reference-variables-from-the-environment-in-data-masked-contexts

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +  ) |>
```suggestion
  dplyr::across(dplyr::starts_with("quantile_"), round, .names = "{.col}_rounded")
  ) |>
```

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +    forecast_date = reference_date,  # rename reference_date to forecast_date
```suggestion
    forecast_date = reference_date,
```

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +    model = model_id, # rename model_id to model
```suggestion
    model = model_id,
```

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +}
If it's not going to overwrite, should error. I think it should just overwrite.

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +if (!file.exists(output_filepath)) {
One reason to use `fs` (even though it adds a dependency) would be to avoid the need for this ifelse. See https://fs.r-lib.org/reference/create.html

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_map_data.R
> +# some required cols, need to update
Is this comment out of date?

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_map_data.R
> +    quantile_0.975_per100k = value /  as.numeric(population) *100000,
```suggestion
    quantile_0.975_per100k = value /  as.numeric(population) * 100000,
```

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_map_data.R
> +  dplyr::mutate(
As above, perhaps worth doing this with `dplyr::across`

2024-12-02 21:45 UTC, dylanhmorris commented on src/code/gen_truth_data.R
> +output_folder_path <- file.path(base_hub_path, "weekly-summaries", ref_date)
As above, `fs::dir_create` might be worth it to simplify this.

2024-12-02 21:48 UTC, dylanhmorris commented on src/code/gen_map_data.R
> +    reference_date = as.Date(reference_date),
```suggestion
    reference_date = as.Date(!!reference_date),
```

2024-12-02 21:48 UTC, dylanhmorris commented on src/code/gen_map_data.R
> +    target_end_date = as.Date(target_end_date),
```suggestion
    target_end_date = as.Date(!!target_end_date),
```

2024-12-02 21:50 UTC, dylanhmorris commented on src/code/gen_truth_data.R
Is there a reason why this should be separate from [`get_target_data.r`](https://github.com/CDCgov/covid19-forecast-hub/blob/main/src/code/get_target_data.r )?

2024-12-02 21:53 UTC, sbidari commented
I think we should exclude the locations indicated [here](https://github.com/CDCgov/covid19-forecast-hub/blob/c6946829b8931b0206901240c8a775a8171ce3da/auxiliary-data/2024-11-23-exclude-locations.json) or at-least a subset of it for the first week (`reference-date = 2024-11-23`)? 

I forgot to mention this in the earlier meeting but had talked to @AFg6K7h4fhy2 previously about this

2024-12-02 21:54 UTC, AFg6K7h4fhy2 commented on src/code/gen_truth_data.R
My argument for "yes" is `get_target_data.r`'s 

(1) exclusions i.e.

```r
exclude_data <- jsonlite::fromJSON("auxiliary-data/exclude_ensemble.json")
excluded_locations <- exclude_data$locations

formatted_data <- covid_data |>
  dplyr::left_join(loc_df, by = c("state" = "abbreviation")) |>
  dplyr::filter(!(location %in% excluded_locations)) |>
  dplyr::select(date, state, value, location)
```

(2) the columns names 

```r
  dplyr::select(
    week_ending_date = date, 
    location, 
    location_name, 
    value
  )
```

and the non-presence of "United States"

```r
# long name "United States" to "US"
  dplyr::mutate(
    location_name = dplyr::if_else(
      location_name == "United States", 
      "US", 
      location_name)
  )
```

2024-12-02 21:55 UTC, dylanhmorris commented on src/code/gen_forecast_data.R
> +  ) |>
Remove extra `)` (fixing my own bug)

```suggestion
  dplyr::across(dplyr::starts_with("quantile_"), round, .names = "{.col}_rounded") |>
```

2024-12-02 21:56 UTC, sbidari commented on src/code/gen_truth_data.R
`get_target_data.r` pulls data starting from the first full week of the new mandatory reporting period but Inform would like historical data included for the visualization.

2024-12-02 22:00 UTC, sbidari commented on src/code/gen_truth_data.R
Combining the two makes sense, the only difference between the two is if `reference-date` is specified during the call to `pull_nhsn` function. I will create a PR for it

2024-12-02 22:35 UTC, AFg6K7h4fhy2 commented
These comments seem all that remain to be addressed:

* <https://github.com/CDCgov/covid19-forecast-hub/pull/118#discussion_r1866677249>
* <https://github.com/CDCgov/covid19-forecast-hub/pull/118#issuecomment-2513008508>
* <https://github.com/CDCgov/covid19-forecast-hub/pull/118#issuecomment-2512722766>

2024-12-02 22:56 UTC, dylanhmorris commented on src/code/gen_truth_data.R
Sounds good. Make an issue?

2024-12-02 22:57 UTC, dylanhmorris commented on src/code/gen_truth_data.R
> (3) the non-presence of "United States"

the target data does contain rows for the US

2024-12-02 22:59 UTC, AFg6K7h4fhy2 commented on src/code/gen_truth_data.R
Sorry. I meant "Inform wants us to convert the long name for the US, United States, to US" whereas we might not want that in `get_target_data.r`.

2024-12-02 23:19 UTC, sbidari commented on src/code/gen_truth_data.R
created an issue #122

2024-12-02 23:36 UTC, sbidari commented
> _The author would appreciate guidance on handling the below_
> 
This is likely due to the duplication of `model_id`s in `model_metadata`. You can try to extract only the unique model_id entries before the `left_join`. Will look into why there are duplicates in the `model_metadata`

2024-12-03 16:39 UTC, sbidari commented on weekly-summaries/2024-11-23/2024-11-23_truth-data.csv
> +2020-09-05,60,American Samoa,NA
We don't want additional territories included in the truth data. It should just have the 50 states, DC and PR

2024-12-03 17:09 UTC, AFg6K7h4fhy2 commented on weekly-summaries/2024-11-23/2024-11-23_truth-data.csv
> +2020-09-05,60,American Samoa,NA
The need `excluded_territories` file will be used to get this.

2024-12-03 17:37 UTC, sbidari approved these changes

2024-12-03 17:39 UTC, sbidari commented
This is ready to merge. Thanks a lot @AFg6K7h4fhy2

2024-12-03 17:39 UTC, merged