Address Inform Feedback Regarding Weekly Summaries Data
CDCgov/covid19-forecast-hub pull request #128
Opened 2024-12-03 17:56 UTC by AFg6K7h4fhy2

For the scope of this PR, please refer to issue #127 .

2024-12-05 19:53 UTC, AFg6K7h4fhy2 commented
A note: the completion of this PR is dependent upon external decisions that currently in the progress of being made. This explains the wait times between commits.

2024-12-11 17:19 UTC, AFg6K7h4fhy2 commented
Further changes in this PR relating to this comment <https://github.com/CDCgov/covid19-forecast-hub/issues/127#issuecomment-2536511633> depend, in the present moment, on some remarks from those who are depending on us.

2024-12-17 15:50 UTC, dylanhmorris approved these changes
Fine to merge, a few thoughts. In general a reminder to prefer meaningful function names to explanatory comments, and in particular to avoid comments like `# set up command line argument parser`

2024-12-17 15:50 UTC, dylanhmorris commented on src/get_forecast_data.R
> +  dplyr::filter(horizon != 3, horizon != -1) |>
I think clearer to do
```suggestion
# filter to horizons included in web summary
  dplyr::filter(horizon %in% 0:2) |>
```

But really I for future-proofing I'd create a variable named `horizons_to_include`, specifiable from the command line. Then this line would become

```suggestion
# filter to horizons included in web summary
  dplyr::filter(horizon %in% !!horizons_to_include) |>
```

2024-12-17 15:50 UTC, dylanhmorris commented on src/get_forecast_data.R
> +#' Rscript get_forecast_data.R --reference_date 2024-11-23 --base_hub_path ../
Can rely on CLI help defined by argparser for this.

2024-12-17 15:50 UTC, dylanhmorris commented on src/get_covid_hosp_data.R
> +  )
This is fine for now, but for future reference good to specific string-formatting of dates explicitly or at least use `glue`
```suggestion
  output_filename <- paste0(
    reference_date, "_covid_target_hospital_admissions_data.csv"
  )
```

2024-12-17 16:03 UTC, sbidari requested changes
Thanks @AFg6K7h4fhy2. 
Two main changes
- removing `-1 time horizon` from `map_data`
- renaming the csv files 

and some minor changes

2024-12-17 16:14 UTC, AFg6K7h4fhy2 commented on src/get_forecast_data.R
> +  dplyr::filter(horizon != 3, horizon != -1) |>
I will make the `horizon_to_include` entry.

2024-12-17 17:36 UTC, AFg6K7h4fhy2 commented
Re: <https://github.com/CDCgov/covid19-forecast-hub/pull/128#issuecomment-2549046703>

Thank you SB for messaging Aida; the map file now has the horizon -1 ignored.

2024-12-17 17:42 UTC, AFg6K7h4fhy2 commented on weekly-summaries/README.md
Not sure what is meant by this. Which heading am I to change?

2024-12-17 17:59 UTC, AFg6K7h4fhy2 commented
Any thoughts SB on having Aida or another external Inform member look at the csvs themselves (in addition to us verifying correctness) today?

2024-12-17 18:23 UTC, AFg6K7h4fhy2 commented on weekly-summaries/README.md
I am silly. I was looking at the main README and ... (oof) forgot about the README that I had made in `weekly-summaries`!

2024-12-17 18:30 UTC, sbidari commented
> Any thoughts SB on having Aida or another external Inform member look at the csvs themselves (in addition to us verifying correctness) today?

I don't necessarily want to increase work for Aida or others at inform, we can let them know they are welcome to review if they'd like to!

2024-12-17 18:31 UTC, sbidari approved these changes

2024-12-17 18:38 UTC, merged