Consider Use Of `pre-commit`
CDCgov/covid19-forecast-hub pull request #147
Opened 2024-12-06 21:46 UTC by AFg6K7h4fhy2

For the scope of this PR, please refer to issue #145 .

2024-12-06 23:19 UTC, dylanhmorris requested changes
Thanks @AFg6K7h4fhy2! Could you resolve the conflicts and then re-request review?

Also, some argument for using [actions/pre-commit](https://github.com/pre-commit/action) rather than the custom CFA one given that this is a public repo

2024-12-10 01:24 UTC, dylanhmorris commented
Action still appears to be the one here [.github/actions/pre-commit/action.yaml](https://github.com/CDCgov/covid19-forecast-hub/pull/147/files#diff-90fbcc557efffbec0e9599bcca56e59c10ac129a9ceb934bde29e5ab943f747c). I was suggesting just using https://github.com/pre-commit/action

2024-12-10 03:35 UTC, AFg6K7h4fhy2 commented
Re: 

Ah, I see. From the link you sent, I was looking at [this file](https://github.com/pre-commit/action/blob/main/action.yml), rather than inside the README, which has this:

```yaml
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
```

2024-12-10 15:53 UTC, dylanhmorris commented on .github/workflows/pre-commit.yaml
> +    - uses: actions/setup-python@v3
```suggestion
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
```

2024-12-11 00:44 UTC, dylanhmorris commented
For the R hooks, need to setup the cache explicitly. See e.g. https://github.com/CDCgov/ww-inference-model/blob/main/.github/workflows/pre-commit.yaml

```yaml
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/R/renv
        key: r-precommit-cache|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
```

2024-12-11 01:08 UTC, dylanhmorris approved these changes
LGTM, thanks @AFg6K7h4fhy2!

2024-12-11 01:09 UTC, merged