update week list of models included in ensemble and code generating it
CDCgov/covid19-forecast-hub pull request #153
Opened 2024-12-10 14:51 UTC by sbidari

2024-12-10 15:13 UTC, dylanhmorris commented on auxiliary-data/2024-12-07-models-to-include-in-ensemble.csv
> -"MOBS-GLEAM_COVID",TRUE
This is removed because they didn't submit for this week, yes?

2024-12-10 15:57 UTC, dylanhmorris commented on src/code/get_ensemble.R
>  )
Can this part be handled by `hubData` constructs? Indeed, afaict right now `hub_content` isn't used at all)

2024-12-10 16:07 UTC, sbidari commented on auxiliary-data/2024-12-07-models-to-include-in-ensemble.csv
> -"MOBS-GLEAM_COVID",TRUE
Yes

2024-12-10 17:17 UTC, sbidari commented on src/code/get_ensemble.R
>  )
Yes, I changed the code to use `hub_content` instead of reading submission file name

2024-12-11 01:02 UTC, dylanhmorris requested changes
A few small but important points

2024-12-11 15:04 UTC, sbidari commented on src/code/get_ensemble.R
> +  model_ids = NULL
That simplifies things, thanks @dylanhmorris.

2024-12-11 15:53 UTC, sbidari commented
Ready for re-review @dylanhmorris 
Made slight changes to what you proposed. I included `model_ids` for all models submitted in a week in the csv file (renamed accordingly) and filter by `designated_model` when creating ensemble.
This will generate a weekly list of models submitted with a column indicating whether or not it was used for ensemble which can be used for the visualization website.

2024-12-11 16:55 UTC, dylanhmorris commented
Nice idea, thanks!

2024-12-11 16:56 UTC, dylanhmorris approved these changes

2024-12-11 16:56 UTC, merged