Create baseline and ensemble
CDCgov/covid19-forecast-hub pull request #24
Opened 2024-10-25 20:23 UTC by sbidari

This PR adds:

R scripts: `get_baseline.r` and `get_ensemble.r` 
- generate and save `CovidHub-quantile-baseline.csv`, `CovidHub-ensemble.csv`, and `model-to-include-in-ensemble.csv` 

GitHub actions workflows: `create_baseline.yaml` and `create_ensemble.yaml` 
- run R scripts as scheduled and commit changes via a PR that hopefully gets merged automatically.

2024-10-25 21:56 UTC, dylanhmorris reviewed
A few minor questions, but looks very good. Thanks, @sbidari. There are also a number of ways I think we can tweak the scripts, but I think those can be separate PRs once we have these working.

2024-10-25 21:56 UTC, dylanhmorris commented on .github/workflows/create_baseline.yaml
> +        push: true
I think we need this, no?
```suggestion
        push: true
        new_branch: auto-baseline
```

2024-10-25 21:56 UTC, dylanhmorris commented on .github/workflows/create_baseline.yaml
> +    - cron: "30 19 * * 3"
Maybe a bit later in case the data posts late? This is 19:30 UTC and we don't really need the baseline much before the deadline (23:00 US/Eastern ==> 03:00 or 04:00 UTC the next day, depending on daylight savings). Maybe a bit before the end of the US/Eastern workday, e.g. 20:30 UTC

```suggestion
    - cron: "30 20 * * 3"
```

2024-10-25 21:56 UTC, dylanhmorris commented on .github/workflows/create_ensemble.yaml
> +    - cron: "30 10 * * 4"
Do we want this to run overnight or in the morning after we've had a chance to manually review any PRs that failed to automerge?

2024-10-25 21:56 UTC, dylanhmorris commented on .github/workflows/create_ensemble.yaml
> +        push: true
```suggestion
        push: true
        new_branch: auto-ensemble
```

2024-10-29 13:25 UTC, sbidari commented on .github/workflows/create_baseline.yaml
> +        push: true
not sure but I will add it to be safe!

2024-10-29 13:28 UTC, sbidari commented on .github/workflows/create_ensemble.yaml
> +    - cron: "30 10 * * 4"
Good point! I think we can wait until next morning.

2024-11-07 00:51 UTC, sbidari commented
Changed workflow files to use gh cli for creating a PR which seemed to work better during testing.

2024-11-07 21:40 UTC, dylanhmorris requested changes
A few suggestions/thoughts. Thanks, @sbidari!

2024-11-07 21:40 UTC, dylanhmorris commented on src/code/get_ensemble.r
> +) |> dplyr::filter(Designated_Model == TRUE)
This section can be simplified and made more robust and readable, I think:

```suggestion
 is_model_designated <- function(yaml_file) {
  yml_data <- yaml::yaml.load_file(yaml_file)
  team_and_model <- glue::glue("{yml_data$team_abbr}-{yml_data$model_abbr}") 
  is_designated <- ifelse("designated_model" %in% names(yml_data), 
                          as.logical(yml_data$designated_model), 
                          FALSE)
  return(list(Model = team_and_model, Designated_Model = is_designated))
}

eligible_models <- purrr::map(yml_files, is_model_designated) |> 
   dplyr::bind_rows() |> 
   dplyr::filter(Designated_Model)
```

2024-11-07 21:40 UTC, dylanhmorris commented on src/code/get_ensemble.r
> +  dplyr::filter(model_id %in% models, location != 78)
Instead of hard-coding this, we should specify a set of excluded locations at minimum at the top of the script or possibly in a distinct file.
```suggestion
  dplyr::filter(model_id %in% models, location != 78)
```

2024-11-07 21:40 UTC, dylanhmorris commented on src/code/get_ensemble.r
> +  dplyr::mutate(output_type_id = as.character(as.numeric(output_type_id)))
Is this double coercion definitely necessary? Presumably the reason is to deal with leading and trailing zeros in quantile levels, so that `output_type_id = 0.250000000` and `output_type_id = .25` and `output_type_id = 0.250` all get grouped together, but if so this should be noted in a comment, and really it might be more robust to do`as.factor(as.numeric(output_type_id))` or even filter the quantiles to be among a pre-specified set of quantiles. Second thing is probably out of scope for now.

```suggestion
  dplyr::mutate(output_type_id = as.character(as.numeric(output_type_id)))
```

2024-11-07 21:40 UTC, dylanhmorris commented on src/code/get_baseline.r
> +      dplyr::filter(time_value >= as.Date("2024-11-01")) |>
This shouldn't be hardcoded here.

2024-11-07 21:40 UTC, dylanhmorris commented on src/code/get_baseline.r
> +    )
we may want to remove this, but let's keep it for now for alignment purposes

2024-11-08 23:30 UTC, sbidari commented on src/code/get_ensemble.r
> +  dplyr::mutate(output_type_id = as.character(as.numeric(output_type_id)))
yes, this was to ensure that leading and trailing zeros were handled appropriately. Used `as.factor(as.numeric(output_type_id))` in https://github.com/CDCgov/covid19-forecast-hub/pull/24/commits/656f5ed19952847067eb17925885bb0274c8fc4f

2024-11-08 23:32 UTC, sbidari commented on src/code/get_ensemble.r
> +  dplyr::filter(model_id %in% models, location != 78)
Used a file to provide excluded locations data as per suggestion, in https://github.com/CDCgov/covid19-forecast-hub/pull/24/commits/656f5ed19952847067eb17925885bb0274c8fc4f

2024-11-08 23:33 UTC, sbidari commented on src/code/get_ensemble.r
> +) |> dplyr::filter(Designated_Model == TRUE)
changed in https://github.com/CDCgov/covid19-forecast-hub/pull/24/commits/656f5ed19952847067eb17925885bb0274c8fc4f

2024-11-12 19:10 UTC, dylanhmorris approved these changes
Thanks, @sbidari. I think we should move after from using `Sys.date` and instead specify the referen'ce date explicitly when we build baselines/ensembles, but that can be a separate PR. Can you make an issue?

2024-11-12 21:47 UTC, merged