update readme to include parquet files and clarification about samples
CDCgov/covid19-forecast-hub pull request #29
Opened 2024-11-06 22:14 UTC by sbidari

2024-11-07 21:09 UTC, dylanhmorris reviewed
A few minor suggestions, thanks @sbidari!

2024-11-07 21:09 UTC, dylanhmorris commented on model-output/README.md
> +The metadata file will be saved within the model-metdata directory in the Hub's GitHub repository, and should have either of the following naming convention:
```suggestion
The metadata file will be saved within the model-metdata directory in the Hub's GitHub repository. It should be a YAML file with base name `{team name}-{model name}`, and extension `.yml` or `.yaml`, e.g.
```

2024-11-07 21:09 UTC, dylanhmorris commented on model-output/README.md
> +    team-model.yml
```suggestion
    exampleteam-examplemodel.yml
    otherteam-othermodel.yaml
```

2024-11-07 21:09 UTC, dylanhmorris commented on model-output/README.md
> +    team-model.yaml
```suggestion
```

2024-11-07 21:09 UTC, dylanhmorris commented on model-output/README.md
>      YYYY-MM-DD-team-model.csv
```suggestion
    {YYYY}-MM-DD}-{team name}-{model name}.csv
```

2024-11-07 21:09 UTC, dylanhmorris commented on model-output/README.md
> +    YYYY-MM-DD-team-model.parquet
```suggestion
    {YYYY-MM-DD date}-{team name}-{model name}.parquet
```

2024-11-07 21:09 UTC, dylanhmorris commented on model-output/README.md
> +    YYYY-MM-DD-team-model.parquet
and then add a concrete example, e.g. 

`2024-11-16-exampleteam-examplemodel.parquet`

2024-11-07 22:19 UTC, sbidari commented on model-output/README.md
> +    YYYY-MM-DD-team-model.parquet
On second thought, I think this is better? 

```suggestion
   {YYYY-MM-DD}-{team}-{model}.parquet
```
since we specify above that `team` is the team name and
 `model` refers to the name of the model.
+ concrete example

2024-11-12 18:44 UTC, dylanhmorris requested changes
A couple very minor wording suggestions; thanks, @sbidari!

2024-11-12 18:44 UTC, dylanhmorris commented on model-output/README.md
> +    {YYYY-MM-DD}-{team}-{model}.parquet
```suggestion
    {YYYY-MM-DD}-{team}-{model}.csv

or

    {YYYY-MM-DD}-{team}-{model}.parquet

depending on whether the team is submitting forecasts as `.csv` files or as `.parquet` files.
```

2024-11-12 18:44 UTC, dylanhmorris commented on model-output/README.md
>  -   "samples".
And change "are either" above "should be one of"

```suggestion
-   `quantile` 
-   `samples`
```

2024-11-12 22:35 UTC, dylanhmorris approved these changes
LGTM

2024-11-12 22:36 UTC, merged