add details about sample target
CDCgov/covid19-forecast-hub pull request #8
Opened 2024-10-16 21:34 UTC by sbidari

add more details re. submitting samples from a marginal/joint distribution with an example data table.

2024-10-23 19:01 UTC, dylanhmorris requested changes
Looks very good, thanks @sbidari! A few tweaks/suggestions.

2024-10-23 19:01 UTC, dylanhmorris commented on model-output/README.md
> +When the predictions are samples, values in the `output_type_id` column are indexes for the samples. The `output_type_id` is used to indicate the dependence across multiple task id variables when sam
```suggestion
When the predictions are samples, values in the `output_type_id` column are indexes for the samples. The `output_type_id` is used to indicate the dependence across multiple task id variables when samples come from a joint predictive distribution. For example, samples from a joint predictive distribution across `horizon`s for a given `location`, will share `output_type_id` for predictions for different horizons within a same `location` as below:
```

2024-10-23 19:01 UTC, dylanhmorris commented on model-output/README.md
> +Here, `output_type_id = s0` specifies that the predictions for horizons -1, 0, and 1 are part of the same joint distribution. More details on sample output can be found in the [hubverse documentation
For extra clarity, give an example of a second location, so people know how to indicate that MA trajectories are _not_ joint with, e.g., `NH` trajectories, but are joint across horizons for each location? And maybe also give an example of a submission of trajectories that are joint across both locations and horizons?

2024-10-24 21:22 UTC, sbidari commented on hub-config/tasks.json
> +                                "max_samples_per_task": 100,
We could maybe request submission in `parquet` format then? Variant nowcasting hub is doing this

2024-10-24 21:33 UTC, dylanhmorris commented on hub-config/tasks.json
> +                                "max_samples_per_task": 100,
I think we probably want to stick with `csv` for alignment with FluSight. We can do some rough calculations on what file size might look like with more samples allowed.

2024-10-24 21:36 UTC, sbidari commented on hub-config/tasks.json
> +                                "max_samples_per_task": 100,
Okay, I can do this and run it by you

2024-10-24 21:37 UTC, dylanhmorris commented on hub-config/tasks.json
> +                                "max_samples_per_task": 100,
Sounds good, thanks!

2024-10-25 19:11 UTC, sbidari commented on model-output/README.md
> +Here, `output_type_id = s0` specifies that the predictions for horizons -1, 0, and 1 are part of the same joint distribution. More details on sample output can be found in the [hubverse documentation
added another example table in https://github.com/CDCgov/covid19-forecast-hub/pull/8/commits/d66668cc241e2a6dfd4583af93c5dfb3584f0b8d

2024-11-05 23:39 UTC, dylanhmorris approved these changes
LGTM!

2024-11-05 23:39 UTC, merged